development:
  adapter: postgresql
  encoding: unicode
  database: carma_quest_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432 

test:
  adapter: postgresql
  encoding: unicode
  database: carma_quest_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432
