development:
  adapter: mysql2
  database: carma_quest
  pool: 5
  username: root
  password: gourav4carma
  host: localhost
  port: 5432 

test:
  adapter: mysql2
  database: carma_quest_test
  pool: 5
  username: root
  password: gourav4carma
  host: localhost
  port: 543